In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#2 dimensional array
b= np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
# get dimensions for a 
a.ndim

1

In [7]:
# get dimensions for b
b.ndim

2

In [9]:
# Get shape for a
a.shape
# its a vector so its only going to tell us one dimension 

(3,)

In [12]:
# Get shape for b
b.shape
# will tell us the rows and columns (2 rows 3 columns)

(2, 3)

In [13]:
#get type for a
a.dtype

dtype('int32')

In [14]:
#get type for b
b.dtype

dtype('float64')

In [15]:
# get size for a
a.itemsize

4

In [16]:
#get total size for a
a.size * a.itemsize

12

In [17]:
# another way to get total size for a
a.nbytes

12

In [ ]:
# accessing/changing specigic elements, rows, columns, etc

In [18]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
# prove that its (2,7)
a.shape

(2, 7)

In [20]:
# get a specific element [r,c]
a[1,5]

13

In [21]:
# get a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
# get a specific column 
a[:,2]

array([ 3, 10])

In [25]:
# getting a little more fancy [startindex:endindex:stepsize]
# if we wanted to get every other element so 2,4,6 
a[0,1:6:2]

array([2, 4, 6])

In [27]:
#change an element
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [28]:
#change series of numbers example replace the [3,10] column
a[:,2]= 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [29]:
#change series of numbers example replace the [3,10] column
a[:,2]= [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [30]:
#3d example

b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print (b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
# get a specific element (work outside in) (first set, second row,second element/ first index)
b[0,1,1]

4

In [32]:
#replace
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [37]:
#replace
b[:,1,:]= [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [38]:
#initializing different types of arrays


In [39]:
# ALL 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
#ALL 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [42]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [43]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [44]:
#any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [46]:
# random decimal numbers 
np.random.rand(4,2,3)

array([[[0.88699744, 0.27362969, 0.74892078],
        [0.34212576, 0.85830809, 0.74015474]],

       [[0.94891865, 0.92757065, 0.49973767],
        [0.3554081 , 0.73699542, 0.41989913]],

       [[0.93546826, 0.35362225, 0.4336918 ],
        [0.00323798, 0.58653839, 0.95169967]],

       [[0.29358729, 0.88726433, 0.16153232],
        [0.47881867, 0.08060844, 0.0042557 ]]])

In [48]:
#random integer values 
np.random.randint(7,size=(3,3))

array([[6, 4, 1],
       [1, 3, 2],
       [0, 6, 1]])

In [49]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
# repeat an array
arr = np.array([[1,2,3]])
r1= np.repeat(arr,3, axis=0)
print (r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [54]:
arr = np.array([[1,2,3]])
r1= np.repeat(arr,3, axis=1)
print (r1)

[[1 1 1 2 2 2 3 3 3]]


In [ ]:
#exercise: border of 5x5 matrix are 1's and inside are all 0s except in the very middle is  9


In [66]:
output= np.ones((5,5),dtype='int32')
print(output)

z=np.zeros((3,3),dtype='int32')
z[1,1]=9
print(z)

output[1:4,1:4]= z
print (output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#mathematics 

In [68]:
a= np.array([1,2,3,4])
print (a)

[1 2 3 4]


In [69]:
a+2

array([3, 4, 5, 6])

In [70]:
a-2

array([-1,  0,  1,  2])

In [71]:
a*2

array([2, 4, 6, 8])

In [72]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [73]:
b= np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [74]:
#a to the second power 
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [75]:
# take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [76]:
# Linear Algebra

In [83]:
a= np.ones((2,3))
print (a)

b= np.full((3,2),2)
print(b)

#columns of first matrix equal to rows of second matrix

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [84]:
# matrix multiplication
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [86]:
# find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

In [88]:
#statistics

In [89]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [90]:
np.min(stats,axis=1)

array([1, 4])

In [93]:
np.min(stats,axis=0)

array([1, 2, 3])

In [92]:
np.max(stats)

6

In [94]:
np.max(stats, axis=1)

array([3, 6])

In [95]:
np.max(stats, axis=0)

array([4, 5, 6])

In [96]:
np.sum(stats)

21

In [98]:
np.sum(stats, axis=0)
#add up sum going downwards

array([5, 7, 9])

In [99]:
#reorganizing arrays

In [103]:
before= np.array([[1,2,3,4],[5,6,7,8]])
print (before)

after= before.reshape((8,1))
print (after)

after= before.reshape((4,2))
print (after)

after= before.reshape((2,2,2))
print (after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [106]:
#vertically stacking vectors 
v1= np.array([1,2,3,4])
v2= np.array([5,6,7,8])

np.vstack([v1,v2])

np.vstack([v1,v1,v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [110]:
#horizontally stacking vectors 
h1= np.ones((2,4))
h2= np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])